theme: jekyll-theme-hacker
title: 351ELEC
github.repository_url: https://github.com/benphelps/351ELEC-pages

sass:
  sass_dir: assets/css

plugins:
  - custom_filter

tipue_search:
  include:
    pages: true
